episode-07/config/routes.rb
Rails.application.routes.draw do
  root(to: "home#index")
  get("about" => "about#index")
  get("posts" => "posts#index")

  # get index
  # get show
  # get new
  # post create
  resources(:consoles)

  namespace :api do
    get("status" => "status#index")
    get("consoles" => "consoles#index")
  end
end

episode-07/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

episode-07/app/models/console.rb
class Console < ActiveRecord::Base
  validates :name, presence: true
  validates :manufacturer, presence: true

  scope :nintendo, -> { where(manufacturer: "Nintendo") }

  def formatted_name
    "#{manufacturer} #{name}"
  end
end

episode-07/app/models/post.rb
class Post < ApplicationRecord
end

episode-07/app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

episode-07/app/controllers/api/consoles_controller.rb
class Api::ConsolesController < ApplicationController
  def index
    if params[:manufacturer].present?
      consoles = Console.where(manufacturer: params[:manufacturer])
    else
      consoles = Console.all
    end

    render(json: { "consoles" => consoles.map(&:formatted_name) })
  end
end

episode-07/app/controllers/api/status_controller.rb
class Api::StatusController < ApplicationController
  def index
    render(json: { 'status' => 'ok' })
  end
end

episode-07/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

episode-07/app/controllers/consoles_controller.rb
class ConsolesController < ApplicationController
  def index
    @consoles = Console.all
  end

  def new
    @console = Console.new
  end

  def create
    console = Console.new(console_params)
    console.save
    redirect_to(consoles_path)
  end

  private

  def console_params
    params.require(:console).permit(:name, :manufacturer)
  end
end

episode-07/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

episode-07/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show update destroy ]

  # GET /posts
  def index
    @posts = Post.all

    render json: { posts: @posts }
  end

  # GET /posts/1
  def show
    render json: @post
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    if @post.save
      render json: @post, status: :created, location: @post
    else
      render json: @post.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      render json: @post
    else
      render json: @post.errors, status: :unprocessable_entity
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy!
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.expect(post: [ :title, :content ])
    end
end

episode-07/app/views/about/index.html.erb
<h1>About</h1>

episode-07/app/views/consoles/index.html.erb
<h1>Consoles</h1>

<%= link_to('Add New Console', new_console_path) %>

<ul>
  <% @consoles.each do |console| %>
    <li>
      <%= console.formatted_name %>
    </li>
  <% end %>
</ul>

episode-07/app/views/consoles/new.html.erb
<h1>New Console Form</h1>

<%= form_for(@console) do |f| %>
  <label>
    Name
    <%= f.text_field(:name) %>
  </label>

  <label>
    Manufacturer
    <%= f.text_field(:manufacturer) %>
  </label>

  <%= f.submit('Create') %>
<% end %>

episode-07/app/views/home/index.html.erb
<h1>Game Tracker</h1>

<%= link_to('About', about_path) %>

episode-07/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestDrivenRspecApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>
  <body>
    <nav>
      <%= link_to('Consoles', consoles_path) %>
    </nav>
    <%= yield %>
  </body>
</html>